Saving last configuration file to .certora_internal/25_09_13_09_50_42_817/run.conf
There is no TAC file. Going to script CertoraProver/certoraBuild.py to main_with_args()
Creating dir /home/manoel/projeto/GasOptimizationCatalog/case-study/conf/.certora_internal/25_09_13_09_50_42_817/.certora_config
In /home/manoel/projeto/GasOptimizationCatalog/case-study/specs/casestudy.spec, found the imports: []
copying spec file /home/manoel/projeto/GasOptimizationCatalog/case-study/specs/casestudy.spec to /home/manoel/projeto/GasOptimizationCatalog/case-study/conf/.certora_internal/25_09_13_09_50_42_817/.certora_sources/.0_casestudy.spec.spec
writing /home/manoel/projeto/GasOptimizationCatalog/case-study/conf/.certora_internal/25_09_13_09_50_42_817/.certora_verify.json
Failed to run Certora Prover locally. Please check the errors below for problems in the specifications (.spec files) or the prover_args defined in the .conf file.
[main] ERROR ALWAYS - Unrecognized option: --multi_contract_resolve
[main] ERROR ALWAYS - Unrecognized option: --multi_contract_resolve
build failed
